# Generated by Django 5.2.1 on 2025-05-27 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookAPI', '0002_book_cover_image'),
        ('borrow_req', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_copies', models.PositiveIntegerField(default=0)),
                ('available_copies', models.PositiveIntegerField(default=0)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='bookAPI.book')),
            ],
        ),
    ]
